SIMONNABINKA/SIMONNABINKA/Controllers/ItemController.cs
using SIMONNABINKA.Models;
using System;
using System.Data;

using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;


namespace SIMONNABINKA.Controllers
{
    public class ItemController : Controller
    {
        loginContext db = new loginContext();

        // GET: Item
        public ActionResult Index()
        {
            return View();
        }
        

        [HttpGet]
        public ActionResult EditMenu()
        {
            ViewBag.header = "Edit Menu";
            ViewBag.date = DateTime.Now.ToString("dd/MM/yyyy");
            ViewBag.EditMenu = "active";
            ViewBag.FK_id_type = new SelectList(db.ms_menu_type.Where(x => x.status == "active"), "PK_id_type", "menu_type");


            return View();
        }

        [HttpPost]
        public ActionResult EditMenu(tbl_menu newMenu)
        {
            using (var tr = db.Database.BeginTransaction())
            {
                try
                {

                    if (ModelState.IsValid)
                    {
                        newMenu.date_created_menu = DateTime.Today;
                        db.tbl_menu.Add(newMenu);
                        db.SaveChanges();
                        int lastMenuId = db.tbl_menu.Max(item => item.PK_id_menu);
                        var changeMenu = db.tbl_menu.Where(s => s.PK_id_menu == lastMenuId).First();
                        string name = Path.GetFileNameWithoutExtension(changeMenu.menu_photo);
                        var ext = Path.GetExtension(changeMenu.menu_photo);
                        string myfile = name + "_" + lastMenuId.ToString() + ext;
                        string path = Path.Combine(Server.MapPath("~/Content/Picture/Menu Picture/"), myfile);
                        changeMenu.menu_photo = myfile;
                        newMenu.imageMenu.SaveAs(path);
                        db.SaveChanges();
                        tr.Commit();

                    }

                }
                catch (Exception ex)
                {

                    //get current controller name
                    //input tbl_logError
                    string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                    loginContext db1 = new loginContext();
                    var session = Session["userID"].ToString();
                    var getUser = db1.tbl_user.AsNoTracking().Where(x => x.username == session).FirstOrDefault();
                    tbl_logError error = new tbl_logError();
                    error.FK_id_user = getUser.PK_id_user;
                    error.error_msg = "page [" + controllerName + "]" + ex.Message;
                    error.error_date = DateTime.UtcNow;
                    db1.tbl_logError.Add(error);
                    db1.SaveChanges();
                    ViewBag.notif = "Page [" + controllerName + "] :" + ex.Message;

                    tr.Rollback();

                }

                return RedirectToAction("CrudMenu");

            }

        }



        [HttpGet]
        public ActionResult EditCategory()
        {
            ViewBag.header = "Edit Category";
            ViewBag.date = DateTime.Now.ToString("dd/MM/yyyy");
            ViewBag.EditCategory = "active";

            List<ms_menu_type> updateListCategory = db.ms_menu_type.ToList();
            TempData["updateListCategory"] = updateListCategory;
            return View();

        }

        [HttpPost]
        public ActionResult EditCategory(ms_menu_type categoryIn)
        {
            using (var tr = db.Database.BeginTransaction())
            {
                try
                {

                    if (ModelState.IsValid)
                    {
                        db.ms_menu_type.Add(categoryIn);
                        db.SaveChanges();

                        tr.Commit();
                        return RedirectToAction("EditCategory");
                    }
                }
                catch (Exception ex)
                {
                    //get current controller name
                    //input tbl_logError
                    string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                    loginContext db1 = new loginContext();
                    var session = Session["userID"].ToString();
                    var getUser = db1.tbl_user.AsNoTracking().Where(x => x.username == session).FirstOrDefault();
                    tbl_logError error = new tbl_logError();
                    error.FK_id_user = getUser.PK_id_user;
                    error.error_msg = "page [" + controllerName + "]" + ex.Message;
                    error.error_date = DateTime.UtcNow;
                    db1.tbl_logError.Add(error);
                    db1.SaveChanges();
                    ViewBag.notif = "Page [" + controllerName + "] :" + ex.Message;

                    tr.Rollback();
                }
                
            }

            return RedirectToAction("EditCategory");
        }

        [HttpGet]
        public ActionResult CrudMenu()
        {
            if (TempData["shortMessage"] != null)
            {
                ViewBag.notif = TempData["shortMessage"].ToString();
            }
            ViewBag.header = "Menu List";
            ViewBag.date = DateTime.Now.ToString("dd/MM/yyyy");
            ViewBag.EditMenu = "active";
            ViewBag.FK_id_type = new SelectList(db.ms_menu_type, "PK_id_type", "menu_type");

            List<tbl_menu> updateListMenu = db.tbl_menu.ToList();
            TempData["updateListMenu"] = updateListMenu;
            return View();

        }

        [HttpPost]
        public ActionResult CrudMenu(tbl_menu menuIn)
        {
            using (var tr = db.Database.BeginTransaction())
            {
                try
                {
                    var updateMenu = db.tbl_menu.Find(menuIn.PK_id_menu);

                    if (ModelState.IsValid)
                    {

                        if (TryUpdateModel(updateMenu))
                        {

                            updateMenu.FK_id_type = menuIn.FK_id_type;
                            updateMenu.itemName = menuIn.itemName;
                            updateMenu.price = menuIn.price;
                            db.SaveChanges();

                            tr.Commit();
                            TempData["shortMessage"] = "success";
                        }
                        return RedirectToAction("CrudMenu");
                    }
                }
                catch (Exception ex)
                {
                    //get current controller name
                    //input tbl_logError
                    string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                    loginContext db1 = new loginContext();
                    var session = Session["userID"].ToString();
                    var getUser = db1.tbl_user.AsNoTracking().Where(x => x.username == session).FirstOrDefault();
                    tbl_logError error = new tbl_logError();
                    error.FK_id_user = getUser.PK_id_user;
                    error.error_msg = "page [" + controllerName + "]" + ex.Message;
                    error.error_date = DateTime.UtcNow;
                    db1.tbl_logError.Add(error);
                    db1.SaveChanges();
                    ViewBag.notif = "Page [" + controllerName + "] :" + ex.Message;

                    tr.Rollback();
                }
            }

            return RedirectToAction("CrudMenu");
        }

        [HttpPost]
        public ActionResult DeleteMenu(tbl_menu id)
        {
            using (var tr = db.Database.BeginTransaction())
            {
                try
                {
                    var deleteMenu = db.tbl_menu.Where(s => s.PK_id_menu == id.PK_id_menu).First();

                    if (TryUpdateModel(deleteMenu))
                    {
                        db.tbl_menu.Remove(deleteMenu);
                        db.SaveChanges();
                        tr.Commit();
                    }
                }
                catch (Exception ex)
                {
                    //get current controller name
                    //input tbl_logError
                    string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
                    loginContext db1 = new loginContext();
                    var session = Session["userID"].ToString();
                    var getUser = db1.tbl_user.AsNoTracking().Where(x => x.username == session).FirstOrDefault();
                    tbl_logError error = new tbl_logError();
                    error.FK_id_user = getUser.PK_id_user;
                    error.error_msg = "page [" + controllerName + "]" + ex.Message;
                    error.error_date = DateTime.UtcNow;
                    db1.tbl_logError.Add(error);
                    db1.SaveChanges();
                    ViewBag.notif = "Page [" + controllerName + "] :" + ex.Message;

                    tr.Rollback();
                }
            }
            return RedirectToAction("CrudMenu");
        }


        //disabled
        [HttpPost]
        public ActionResult Delete(ms_menu_type id)
        {
            var deleteCategory = db.ms_menu_type.Where(s => s.PK_id_type == id.PK_id_type ).First();
            
            if (TryUpdateModel(deleteCategory))
            {
                db.ms_menu_type.Remove(deleteCategory);
                db.SaveChanges();

            }
            return RedirectToAction("EditCategory");
        }


        [HttpPost]
        public ActionResult Edit(ms_menu_type idIn)
        {
            var updateStatus = db.ms_menu_type.Find(idIn.PK_id_type);
            if (TryUpdateModel(updateStatus))
            {
                updateStatus.status = idIn.status;

SIMONNABINKA/SIMONNABINKA/Views/Item/Delete.cshtml
@model SIMONNABINKA.Models.ms_menu_type

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ms_menu_type</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.menu_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.menu_type)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SIMONNABINKA/SIMONNABINKA/Views/Item/Edit.cshtml
@model SIMONNABINKA.Models.ms_menu_type

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ms_menu_type</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PK_id_type)

        <div class="form-group">
            @Html.LabelFor(model => model.menu_type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.menu_type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.menu_type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SIMONNABINKA/SIMONNABINKA/Views/Item/EditCategory.cshtml
@model SIMONNABINKA.Models.ms_menu_type
@{
    ViewBag.Title = "EditCategory";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#dataTables').DataTable({
            orderCellsTop: true,
            paging: true,
            search: true
        });
    });

    $(function () {
        $('#addModal', '#deleteModal', '#editModal').on('show.bs.modal', function (e) {
        });

        $("[data-edit]").click(function (e) {
            e.preventDefault();
            var id = $(this).data("edit");
            $('.editModal-title').text('Edit for ID  = ' + id);
            $("#idEdit").val(id);
        });

        $("[data-delete]").click(function (e) {
            e.preventDefault();
            var id = $(this).data("delete");
            $('.deleteModal-title').text('Delete ID  = ' + id);

            $("#idDelete").val(id);
        });

        $("[data-value]").click(function (e) {
            e.preventDefault();
            var value = $(this).data("value");
            $("#Value").val(value);
        });

    });
    
</script>

<div class="container-fluid">
    <!-- Page Heading -->
    <br><h1 class="h3 mb-2 text-gray-800">@ViewBag.header</h1><br>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">@ViewBag.date</h6>
        </div>
        @{
                List<SelectListItem> status = new List<SelectListItem>();
                status.Add(new SelectListItem
                {
                    Text = "Active",
                    Value = "active",
                    Selected = true
                });
                status.Add(new SelectListItem
                {
                    Text = "Deactive",
                    Value = "deactive"

                });

        }

        <div class="card-body">
            <div class="table-responsive">
                <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="mb-3">

                        <button data-toggle="modal" data-target="#addModal" class="card bg-primary text-white shadow px-3 py-2  d-inline">Add Category</button>
                    </div>
                    @*<div class="col-sm-12 col-md-6"><div class="dataTables_length" id="dataTable_length"><label>Show <select name="dataTable_length" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> Entries</label></div></div><div class="col-sm-12 col-md-6"><div id="dataTable_filter" class="dataTables_filter"></div></div>*@
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-bordered table-striped dataTable" id="dataTables" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                <thead>
                                    <tr role="row" class="text-center">
                                        <th>
                                            @Html.LabelFor(model => model.PK_id_type, "ID Category")
                                        </th>
                                        <th>
                                            @Html.LabelFor(model => model.menu_type, "Category")
                                        </th>
                                        <th>
                                            @Html.LabelFor(model => model.status, "Status")
                                        </th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in (List<SIMONNABINKA.Models.ms_menu_type>)TempData["updateListCategory"])
                                    {
                                        <tr role="row" class="odd text-center">
                                            <td>
                                                @Html.DisplayFor(modelItem => item.PK_id_type)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.menu_type)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.status)
                                            </td>
                                            <td>
                                                @*<button data-toggle="modal" data-target="#deleteModal" data-delete="@item.PK_id_type" class="card bg-danger text-white shadow px-3 py-2  d-inline">Delete</button>*@
                                                <button data-toggle="modal" data-target="#editModal" data-edit="@item.PK_id_type" data-value="@item.menu_type" class="btn btn-primary">Edit</button>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <div class="modal" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        @using (Html.BeginForm("EditCategory", "Item", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                                        {
                                            <div class="modal-header">
                                                <h5 class="addmodal-title custom_align">Add</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">

                                                <div class="form-group">
                                                    @Html.LabelFor(model => model.menu_type, "Category", htmlAttributes: new { @class = "control-label col-md-4" })
                                                    <div class="col-md-10">
                                                        @Html.EditorFor(model => model.menu_type, new { htmlAttributes = new { @class = "form-control" } })
                                                        @Html.ValidationMessageFor(model => model.menu_type, "", new { @class = "text-danger" })
                                                    </div>
                                                    <br />
                                                    @Html.LabelFor(model => model.status, "Status", htmlAttributes: new { @class = "control-label col-md-4" })
                                                    <div class="col-md-10">
                                                        @Html.DropDownListFor(model => model.status, status, null, htmlAttributes: new { @class = "form-control" })
                                                        @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-success" data-save>Add</button>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>


                            <div class="modal" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        @using (Html.BeginForm("Delete", "Item", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                                        {
                                            <div class="modal-header">
                                                <h5 class="deleteModal-title custom_align"></h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                @Html.HiddenFor(model => model.PK_id_type, new { id = "idDelete" })
                                                <h5 class="text-center">Are You Sure ? </h5>
                                            </div>

                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-danger" data-save>Delete</button>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>



                            <div class="modal" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        @using (Html.BeginForm("Edit", "Item", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                                        {
                                            <div class="modal-header">
                                                <h5 class="editModal-title custom_align"></h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                @Html.HiddenFor(model => model.PK_id_type, new { id = "idEdit" })

                                                @Html.LabelFor(model => model.menu_type, "Category", htmlAttributes: new { @class = "control-label col-md-4" })
                                                <div class="col-md-10">
                                                    @Html.TextBoxFor(model => model.menu_type, new { id = "Value", @class = "form-control" })
                                                    @Html.ValidationMessageFor(model => model.menu_type, "", new { @class = "text-danger" })
                                                </div>
                                                <br />
                                                @Html.LabelFor(model => model.status, "Status", htmlAttributes: new { @class = "control-label col-md-4" })
                                                <div class="col-md-10">
                                                    @Html.DropDownListFor(model => model.status, status, null, htmlAttributes: new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                                                </div>
                                            </div>

                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-danger" data-save>Change</button>
                                            </div>
                                         }
                                    </div>
                                </div>
                            </div>

                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

SIMONNABINKA/SIMONNABINKA/Views/Item/EditMenu.cshtml
@model SIMONNABINKA.Models.tbl_menu
@{
    ViewBag.Title = "EditMenu";
}

@using (Html.BeginForm("EditMenu", "Item", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    <div class="container-fluid">
        <!-- Page Heading -->
        <br>
        <h1 class="h3 mb-2 text-gray-800">Add Menu</h1><br>
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">@ViewBag.date</h6>
            </div>
            <form action="#" method="POST">
                <div class="card-body row">
                    <div class="text-center w-50 p-3">
                        <center>
                            <div class="imgWrap" style="width:300px;">
                                <img src="~/Content/Picture/Menu Picture/Food/Food.png" id="imgView" class="card-img-top img-fluid">
                            </div><br />
                            <small>file must be lower than 1mb<span style="color:red;">*</span></small>
                            <div class="custom-file w-75">
                                @* <input type="file" id="inputFile" class="imgFile custom-file-input" aria-describedby="inputGroupFileAddon01">*@
                                @Html.TextBoxFor(model => model.imageMenu, new { type = "file", @class = "input-file imgFile", @id = "inputFile", required = "required" })
                                <label class="custom-file-label" for="inputFile">Choose file</label>
                            </div>
                        </center>
                    </div>
                    <div class="card-row">
                        @Html.HiddenFor(model => model.menu_photo, new { id = "idName" })
      
                        <div class="form-group">
                            @Html.LabelFor(model => model.itemName, "Menu Name", htmlAttributes: new { @class = "control-label" })<span style="color:red;">*</span>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.itemName, new { htmlAttributes = new { @class = "form-control", required="required" }, })
                                @Html.ValidationMessageFor(model => model.itemName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.price, "Price", htmlAttributes: new { @class = "control-label" })<span style="color:red;">*</span>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control", required = "required" }, })
                                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.stock, "Stock", htmlAttributes: new { @class = "control-label" })<span style="color:red;">*</span>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.stock, new { htmlAttributes = new { @class = "form-control", required = "required" }, })
                                @Html.ValidationMessageFor(model => model.stock, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.FK_id_type, "Category", htmlAttributes: new { @class = "control-label" })<span style="color:red;">*</span>
                            <div class="col-md-10">

                                @Html.DropDownListFor(model => model.FK_id_type, (SelectList)ViewBag.FK_id_type, new { @class = "form-control", required = "required" })
                                @Html.ValidationMessageFor(model => model.FK_id_type, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <input type="submit" name="add" class="form-control btn btn-primary" value="Add">
                    </div>
                    <div class="float-right mt-2">

                    </div>
                </div>
            </form>
        </div>

    </div>
}

    @*upload pic script*@
    <script src="~/Content/js/scripts.js"></script>
    <script>
        //photo size validation, max size 1mb
        var uploadField = document.getElementById("inputFile");

        uploadField.onchange = function () {
            if (this.files[0].size > 1000000) {
                alert("File is too big! size must be lower than 1mb");
                this.value = "";
            };
        };
        //photo size validation

        $("#inputFile").change(function (event) {
            fadeInAdd();
            getURL(this);
        });

        $("#inputFile").on('click', function (event) {
            fadeInAdd();
        });

        function getURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                var filename = $("#inputFile").val();
                filename = filename.substring(filename.lastIndexOf('\\') + 1);
                reader.onload = function (e) {
                    debugger;
                    $('#imgView').attr('src', e.target.result);
                    $('#imgView').hide();
                    $('#imgView').fadeIn(500);
                    $('.custom-file-label').text(filename);
                    $("#idName").val(filename);
                }
                reader.readAsDataURL(input.files[0]);
            }
            $(".alert").removeClass("loadAnimate").hide();
        }

        function fadeInAdd() {
            fadeInAlert();
        }
        function fadeInAlert(text) {
            $(".alert").text(text).addClass("loadAnimate");
        }
    </script>